DROP TABLE IF EXISTS `tb_mmt_admin`;

CREATE TABLE `tb_mmt_admin` (
  `ADMIN_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '관리자 ID',
  `NOW_PASSWD` varchar(128) DEFAULT NULL COMMENT '비밀번호',
  `PREV_PASSWD` varchar(128) DEFAULT NULL COMMENT '이전 비밀번호',
  `PASSWD_WRONG_COUNT` int(11) NOT NULL DEFAULT '0' COMMENT '비밀번호 틀린 횟수',
  `NICKNAME` varchar(128) NOT NULL DEFAULT '' COMMENT '사용자한글명',
  `JOBTITLE` varchar(20) NOT NULL DEFAULT '' COMMENT '직책명',
  `TEL` varchar(128) DEFAULT NULL COMMENT '전화번호',
  `EMAIL` varchar(128) DEFAULT NULL COMMENT '이메일',
  `LAST_CONNECT_TIME` datetime DEFAULT NULL COMMENT '최종접속일시',
  `DEL_YN` varchar(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부',
  `CREATE_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '등록자',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일',
  `UPDATE_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일',
  PRIMARY KEY (`ADMIN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='관리자';

DROP TABLE IF EXISTS `tb_mmt_app`;

CREATE TABLE `tb_mmt_app` (
  `APP_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '앱 코드',
  `DEV_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '개발사 아이디',
  `APP_STATUS_CODE` varchar(20) NOT NULL DEFAULT '1' COMMENT '앱 진행상태코드',
  `APP_NAME` varchar(40) NOT NULL DEFAULT '' COMMENT '앱 명',
  `APP_DESC` varchar(100) DEFAULT NULL COMMENT '앱 설명',
  `APP_PACKAGE` varchar(40) DEFAULT NULL COMMENT '앱 패키지',
  `APP_CHANNEL` varchar(20) DEFAULT NULL COMMENT '앱 채널',
  `STATUS_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '상태코드',
  `CREATE_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '등록자',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일',
  `UPDATE_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일',
  PRIMARY KEY (`APP_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='앱';

DROP TABLE IF EXISTS `tb_mmt_common_code`;

CREATE TABLE `tb_mmt_common_code` (
  `GRP_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '그룹 코드',
  `COMMON_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '공통코드',
  `SEQ` int(11) NOT NULL DEFAULT '1' COMMENT '순번',
  `COMMON_CODE_NAME` varchar(20) NOT NULL DEFAULT '' COMMENT '공통 코드명',
  `COMMON_CODE_DESC` varchar(100) DEFAULT NULL COMMENT '공통 코드 설명',
  `COMMON_CODE_VAL` varchar(20) NOT NULL DEFAULT '' COMMENT '공통 코드값',
  `COMMON_CODE_VAL_DESC` varchar(100) DEFAULT NULL COMMENT '공통 코드값 설명',
  `CREATE_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '등록자',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일',
  `UPDATE_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일',
  PRIMARY KEY (`GRP_CODE`,`COMMON_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='공통코드';

DROP TABLE IF EXISTS `tb_mmt_dev_company`;

CREATE TABLE `tb_mmt_dev_company` (
  `DEV_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '개발사 아이디',
  `COMPANY_NAME` varchar(100) NOT NULL DEFAULT '' COMMENT '개발사명',
  `CREATE_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '등록자',
  `CREATE_YMD` varchar(8) NOT NULL DEFAULT '' COMMENT '등록일',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록시간',
  `UPDATE_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일',
  PRIMARY KEY (`DEV_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='개발사';

DROP TABLE IF EXISTS `tb_mmt_grp_code`;

CREATE TABLE `tb_mmt_grp_code` (
  `GRP_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '그룹 코드',
  `GRP_CODE_NAME` varchar(20) DEFAULT NULL COMMENT '그룹 코드명',
  `GRP_CODE_DESC` varchar(100) DEFAULT NULL COMMENT '그룹 코드 설명',
  `STATUS_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '사용여부',
  `CREATE_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '등록자',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일',
  `UPDATE_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일',
  PRIMARY KEY (`GRP_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='공통그룹코드';

DROP TABLE IF EXISTS `tb_mmt_file`;

CREATE TABLE `tb_mmt_file` (
  `FILE_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '파일 아이디',
  `FILE_NAME` varchar(100) NOT NULL DEFAULT '' COMMENT '파일명',
  `ORIGINAL_FILE_NAME` varchar(100) NOT NULL DEFAULT '' COMMENT '원본파일명',
  `FILE_SIZE` int(11) NOT NULL DEFAULT '0' COMMENT '파일 사이즈',
  `FILE_SAVE_PATH` varchar(200) DEFAULT NULL COMMENT '파일 저장 경로',
  `FILE_URL` varchar(100) DEFAULT NULL COMMENT '파일 URL',
  `STATUS_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '상태코드',
  `CREATE_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '등록일시',
  PRIMARY KEY (`FILE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=74 DEFAULT CHARSET=utf8 COMMENT='이미지 파일';

DROP TABLE IF EXISTS `tb_mmt_menu`;

CREATE TABLE `tb_mmt_menu` (
  `MENU_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '메뉴 아이디',
  `SYSTEM_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '시스템 코드',
  `DEPTH` int(11) NOT NULL DEFAULT '1' COMMENT '메뉴레벨',
  `SEQ` int(11) NOT NULL DEFAULT '1' COMMENT '순번',
  `PARENT_MENU_ID` varchar(20) DEFAULT NULL COMMENT '부모 메뉴 아이디',
  `MENU_NAME` varchar(40) NOT NULL DEFAULT '' COMMENT '메뉴명',
  `LINK_URL` text COMMENT '링크',
  `CREATE_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '등록자',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일',
  `UPDATE_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일',
  PRIMARY KEY (`MENU_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='모멘티 메뉴';

DROP TABLE IF EXISTS `tb_mmt_moment`;

CREATE TABLE `tb_mmt_moment` (
  `MOMENT_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '모멘티 아이디',
  `APP_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '앱 코드',
  `MOMENT_STATUS_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '모멘티 진행상태코드',
  `MOMENT_NAME` varchar(40) NOT NULL DEFAULT '' COMMENT '모멘티명',
  `MOMENT_DESC` varchar(100) DEFAULT NULL COMMENT '모멘티 설명',
  `EMOTION_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '이모션구분코드',
  `SEQ` int(11) NOT NULL DEFAULT '1' COMMENT '모멘트순번',
  `STATUS_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '상태코드',
  `DISPLAY_LOCATION_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '위치 구분 코드',
  `MOMENT_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '모멘티 코드',
  `CREATE_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '등록자',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일시',
  `UPDATE_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`MOMENT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8 COMMENT='모멘티';

DROP TABLE IF EXISTS `tb_mmt_package`;

CREATE TABLE `tb_mmt_package` (
  `PKG_ID` int(10) NOT NULL AUTO_INCREMENT COMMENT '패키지 아이디',
  `PKG_NAME` varchar(40) NOT NULL DEFAULT '' COMMENT '패키지명',
  `PKG_DESC` varchar(100) DEFAULT NULL COMMENT '패키지 설명',
  `STATUS_CODE` varchar(20) NOT NULL DEFAULT '',
  `CREATE_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '등록자',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일',
  `UPDATE_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일',
  PRIMARY KEY (`PKG_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8 COMMENT='모멘티 패키지';

DROP TABLE IF EXISTS `tb_mmt_package_moment`;

CREATE TABLE `tb_mmt_package_moment` (
  `MOMENT_ID` int(11) NOT NULL DEFAULT '0' COMMENT '모멘티 아이디',
  `PKG_ID` int(11) NOT NULL DEFAULT '0' COMMENT '패키지 아이디',
  `CREATE_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '등록자',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일',
  `UPDATE_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일',
  PRIMARY KEY (`MOMENT_ID`,`PKG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='패키지 모멘티 목록';

DROP TABLE IF EXISTS `tb_mmt_reward`;

CREATE TABLE `tb_mmt_reward` (
  `RWD_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '리워드 아이디',
  `RWD_NAME` varchar(100) NOT NULL DEFAULT '' COMMENT '리워드명',
  `RWD_DESC` varchar(200) DEFAULT NULL COMMENT '리워드설명',
  `BRAND_NAME` varchar(40) DEFAULT NULL COMMENT '브랜드명',
  `RWD_IMAGE_ID` int(11) NOT NULL DEFAULT '0' COMMENT '리워드 이미지 아이디',
  `RWD_NOTI_IMAGE_ID` int(11) NOT NULL DEFAULT '0' COMMENT '리워드 노티 이미지 아이디',
  `STATUS_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '상태코드',
  `BRAND_DISPLAY_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '브랜드노출여부',
  `CREATE_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '등록자',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일',
  `UPDATE_ID` varchar(20) DEFAULT NULL COMMENT '수정자 아이디',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일',
  PRIMARY KEY (`RWD_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8 COMMENT='리워드';

DROP TABLE IF EXISTS `tb_mmt_grp_coupon`;

CREATE TABLE `tb_mmt_grp_coupon` (
  `GRP_COUPON_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '쿠폰 그룹 아이디',
  `GRP_COUPON_NAME` varchar(100) NOT NULL DEFAULT '' COMMENT '쿠폰 그룹명',
  `COUPON_DISPLAY_TITLE` varchar(100) DEFAULT NULL,
  `STATUS_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '상태코드',
  `REG_STATUS_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '등록상태코드',
  `TEMPLATE_IMAGE_ID` int(11) NOT NULL DEFAULT '0' COMMENT '쿠폰 템플릿 이미지 아이디',
  `COUPON_TYPE_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '연동쿠폰타입코드',
  `INTRO_MSG_1` varchar(40) DEFAULT NULL COMMENT '이용안내1',
  `INTRO_MSG_2` varchar(40) DEFAULT NULL COMMENT '이용안내2',
  `INTRO_MSG_3` varchar(40) DEFAULT NULL COMMENT '이용안내3',
  `INTRO_MSG_4` varchar(40) DEFAULT NULL COMMENT '이용안내4',
  `INTRO_MSG_5` varchar(40) DEFAULT NULL COMMENT '이용안내5',
  `EXPIRE_YMD` varchar(8) NOT NULL DEFAULT '' COMMENT '쿠폰사용만료일',
  `USE_PLACE` varchar(40) DEFAULT NULL COMMENT '사용처',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일시',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`GRP_COUPON_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COMMENT='쿠폰 그룹';

DROP TABLE IF EXISTS `tb_mmt_coupon`;

CREATE TABLE `tb_mmt_coupon` (
  `COUPON_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '쿠폰고유아이디',
  `GRP_COUPON_ID` int(11) NOT NULL DEFAULT '0' COMMENT '쿠폰 그룹 아이디',
  `COUPON_NUMBER` varchar(20) NOT NULL DEFAULT '' COMMENT '연동쿠폰고유번호',
  `CAMPAIGN_ID` int(11) DEFAULT NULL COMMENT '캠페인 아이디',
  `COUPON_STATUS_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '쿠폰상태코드',
  `COUPON_IMAGE_FILE_NAME` varchar(100) DEFAULT NULL COMMENT '쿠폰 이미지 파일명',
  `COUPON_IMAGE_FILE_SIZE` int(11) DEFAULT NULL COMMENT '쿠폰 이미지 파일 사이즈',
  `COUPON_IMAGE_URL` varchar(100) DEFAULT NULL COMMENT '쿠폰 이미지 URL',
  `COUPON_USE_YN` varchar(20) NOT NULL DEFAULT 'USE_N' COMMENT '쿠폰사용여부',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일시',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`COUPON_ID`),
  UNIQUE KEY `UK_COUPON_NUMBER` (`GRP_COUPON_ID`,`COUPON_NUMBER`)
) ENGINE=InnoDB AUTO_INCREMENT=132790 DEFAULT CHARSET=utf8 COMMENT='쿠폰';

DROP TABLE IF EXISTS `tb_mmt_intro`;

CREATE TABLE `tb_mmt_intro` (
  `INTRO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `INTRO_STATUS_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '인트로 진행 상태 코드',
  `INTRO_NAME` varchar(50) NOT NULL DEFAULT '' COMMENT '인트로명',
  `INTRO_DESC` varchar(50) NOT NULL DEFAULT '' COMMENT '인트로 설명',
  `INTRO_MESSAGE` varchar(200) NOT NULL DEFAULT '' COMMENT '인트로 메시지',
  `START_YMD` varchar(8) NOT NULL DEFAULT '' COMMENT '인트로 시작일시',
  `END_YMD` varchar(8) NOT NULL DEFAULT '' COMMENT '인트로 종료일시',
  `START_HMS` varchar(6) NOT NULL DEFAULT '' COMMENT '타겟 시작시간',
  `END_HMS` varchar(6) NOT NULL DEFAULT '' COMMENT '타겟 종료시간',
  `CREATE_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '등록자',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일시',
  `UPDATE_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`INTRO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='인트로';

DROP TABLE IF EXISTS `tb_mmt_intro_app`;

CREATE TABLE `tb_mmt_intro_app` (
  `APP_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '앱 코드',
  `INTRO_ID` int(11) NOT NULL DEFAULT '0' COMMENT '인트로 아이디',
  `CREATE_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '등록자',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일시',
  `UPDATE_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`APP_CODE`,`INTRO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='인트로 앱';

DROP TABLE IF EXISTS `tb_mmt_campaign`;

CREATE TABLE `tb_mmt_campaign` (
  `CAMPAIGN_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '캠페인 아이디',
  `RWD_ID` int(11) DEFAULT NULL COMMENT '리워드 아이디',
  `PKG_ID` int(11) NOT NULL DEFAULT '0' COMMENT '패키지 아이디',
  `CAMPAIGN_STATUS_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '캠페인진행 상태코드',
  `STATUS_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '상태코드',
  `CAMPAIGN_NAME` varchar(40) NOT NULL DEFAULT '' COMMENT '캠페인명',
  `CAMPAIGN_DESC` varchar(100) DEFAULT NULL COMMENT '캠페인 설명',
  `CAMPAIGN_START_YMD` varchar(8) NOT NULL DEFAULT '' COMMENT '캠페인 시작일',
  `CAMPAIGN_END_YMD` varchar(8) NOT NULL DEFAULT '' COMMENT '캠페인 종료일',
  `TARGET_START_HMS` varchar(6) NOT NULL DEFAULT '' COMMENT '타겟시작시간',
  `TARGET_END_HMS` varchar(6) NOT NULL DEFAULT '' COMMENT '타겟종료시간',
  `PRE_MESSAGE` varchar(100) DEFAULT NULL COMMENT '참여 전 메시지',
  `ING_MESSAGE` varchar(100) DEFAULT NULL COMMENT '참여 중 메시지',
  `ACTION_TYPE_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '액션 타입 코드',
  `OFFER_TITLE` varchar(40) NOT NULL DEFAULT '' COMMENT 'Offer pops 제목',
  `OFFER_MESSAGE` varchar(100) NOT NULL DEFAULT '' COMMENT 'Offer pops 메시지',
  `OFFER_CANCEL_TITLE` varchar(40) DEFAULT NULL COMMENT 'Offer pops 취소버튼명',
  `OFFER_CONFIRM_TITLE` varchar(40) DEFAULT NULL COMMENT 'Offer pops 확인버튼명',
  `OFFER_IMAGE_ID` int(11) NOT NULL DEFAULT '0' COMMENT 'Offer pops 아이콘 이미지 파일 아이디',
  `CONGRATURATE_TITLE` varchar(40) NOT NULL DEFAULT '' COMMENT '축하 pops 제목',
  `CONGRATURATE_MESSAGE` varchar(100) NOT NULL DEFAULT '' COMMENT '축하 pops 메시지',
  `CONGRATURATE_CONFIRM_TITLE` varchar(40) DEFAULT NULL COMMENT '축하 pops 확인버튼명',
  `GRP_COUPON_ID` int(11) DEFAULT NULL COMMENT '쿠폰 그룹 아이디',
  `CAMPAIGN_TARGET_COUNT` int(11) DEFAULT NULL COMMENT '캠페인 목표 개수',
  `CREATE_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '등록자',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일시',
  `UPDATE_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`CAMPAIGN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COMMENT='캠페인';

DROP TABLE IF EXISTS `tb_mmt_treats`;

CREATE TABLE `tb_mmt_treats` (
  `CAMPAIGN_ID` int(11) NOT NULL DEFAULT '0' COMMENT '캠페인 아이디',
  `OUTLINK_CATEGORY_CODE` varchar(20) DEFAULT NULL COMMENT '아웃링크 구분 코드',
  `OUTLINK_TITLE` varchar(40) DEFAULT NULL COMMENT '아웃링크 제목',
  `OUTLINK_CONTENTS` varchar(100) DEFAULT NULL COMMENT '아웃링크 내용',
  `OUTLINK_BUTTON_TITLE` varchar(40) DEFAULT NULL COMMENT '아웃링크 버튼명',
  `OUTLINK_BUTTON_DESC` varchar(100) DEFAULT NULL,
  `OUTLINK_URL` varchar(100) DEFAULT NULL COMMENT '아웃링크 URL',
  `WEBVIEW_TITLE` varchar(40) DEFAULT NULL COMMENT '웹뷰 제목',
  `OUTLINK_APP_PACKAGE` varchar(40) DEFAULT NULL COMMENT '아웃링크 앱 패키지명',
  `AUTO_COUPON_DOWNLOAD_YN` varchar(1) NOT NULL DEFAULT 'N' COMMENT '자동쿠폰다운로드여부',
  `AUTO_COUPON_DOWNLOAD_MESSAGE` varchar(100) DEFAULT NULL COMMENT '자동쿠폰다운로드메시지',
  `CREATE_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '등록자',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일시',
  `UPDATE_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`CAMPAIGN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Treats';

DROP TABLE IF EXISTS `tb_mmt_information`;

CREATE TABLE `tb_mmt_information` (
  `INFORMATION_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '인포메이션 아이디',
  `INFORMATION_STATUS_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '인포메이션 진행 상태 코드',
  `INFORMATION_NAME` varchar(50) NOT NULL DEFAULT '' COMMENT '인포메이션명',
  `INFORMATION_DESC` varchar(50) DEFAULT '' COMMENT '인포메이션 설명',
  `INFORMATION_TITLE` varchar(100) NOT NULL DEFAULT '' COMMENT '인포메이션 제목',
  `INFORMATION_MESSAGE` varchar(200) NOT NULL DEFAULT '' COMMENT '인포메이션 메시지',
  `INFORMATION_IMAGE_ID` int(11) NOT NULL DEFAULT '0' COMMENT '인포메이션 이미지 아이디',
  `PKG_ID` int(11) NOT NULL DEFAULT '0' COMMENT '패키지 아이디',
  `START_YMD` varchar(8) NOT NULL DEFAULT '' COMMENT '시작일',
  `END_YMD` varchar(8) NOT NULL DEFAULT '' COMMENT '종료일',
  `START_HMS` varchar(6) NOT NULL DEFAULT '' COMMENT '타겟 시작시간',
  `END_HMS` varchar(6) NOT NULL DEFAULT '' COMMENT '타겟 종료시간',
  `CONFIRM_BUTTON_TITLE` varchar(20) DEFAULT NULL COMMENT '확인 버튼명',
  `CANCEL_BUTTON_TITLE` varchar(20) DEFAULT NULL COMMENT '취소버튼명',
  `STATUS_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '상태코드',
  `CONFIRM_MESSAGE` varchar(100) DEFAULT NULL COMMENT '확인 후 메시지',
  `CREATE_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '등록자',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일시',
  `UPDATE_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`INFORMATION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8 COMMENT='인포메이션';

DROP TABLE IF EXISTS `tb_mmt_information_history`;

CREATE TABLE `tb_mmt_information_history` (
  `USER_ID` int(11) NOT NULL DEFAULT '0' COMMENT '사용자 아이디',
  `INFORMATION_ID` int(11) NOT NULL DEFAULT '0' COMMENT '인포메이션 아이디',
  `RESPONSE_YN` varchar(1) NOT NULL DEFAULT 'N' COMMENT '응답여부',
  `CREATE_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '등록일시',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`USER_ID`,`INFORMATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='인포메이션 수신 이력';

DROP TABLE IF EXISTS `tb_mmt_floating`;

CREATE TABLE `tb_mmt_floating` (
  `CAMPAIGN_ID` int(11) NOT NULL DEFAULT '0' COMMENT '캠페인 아이디',
  `ICON_IMG_FILE_ID` int(11) DEFAULT NULL COMMENT '아이콘 이미지 파일 아이디',
  `MESSAGE1` varchar(20) NOT NULL DEFAULT '' COMMENT '메시지1',
  `MESSAGE2` varchar(20) NOT NULL DEFAULT '' COMMENT '메시지2',
  `OUTLINK_CATEGORY_CODE` varchar(20) DEFAULT NULL COMMENT '아웃링크 구분 코드',
  `OUTLINK_TITLE` varchar(40) DEFAULT NULL COMMENT '아웃링크 제목',
  `OUTLINK_CONTENTS` varchar(100) DEFAULT NULL COMMENT '아웃링크 내용',
  `OUTLINK_BUTTON_TITLE` varchar(40) DEFAULT NULL COMMENT '아웃링크 버튼명',
  `OUTLINK_BUTTON_DESC` varchar(100) DEFAULT NULL COMMENT '아웃링크 버튼 설명',
  `OUTLINK_URL` varchar(100) DEFAULT NULL COMMENT '아웃링크 URL',
  `WEBVIEW_TITLE` varchar(40) DEFAULT NULL COMMENT '웹뷰 제목',
  `OUTLINK_APP_PACKAGE` varchar(40) DEFAULT NULL COMMENT '아웃링크 앱 패키지명',
  `CREATE_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '등록자',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일시',
  `UPDATE_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`CAMPAIGN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Floating';

DROP TABLE IF EXISTS `tb_mmt_weblink`;

CREATE TABLE `tb_mmt_weblink` (
  `CAMPAIGN_ID` int(11) NOT NULL DEFAULT '0' COMMENT '캠페인 아이디',
  `WEBVIEW_TITLE` varchar(100) NOT NULL DEFAULT '' COMMENT '웹뷰 제목',
  `WEBLINK_URL` varchar(100) NOT NULL DEFAULT '' COMMENT 'Web Link URL',
  `REWARD_USE_YN` varchar(1) NOT NULL DEFAULT 'Y' COMMENT '리워드 사용여부',
  `NO_REWARD_TITLE` varchar(100) DEFAULT NULL COMMENT '노 리워드 제목',
  `NO_REWARD_MESSAGE` varchar(200) DEFAULT NULL COMMENT '노 리워드 메시지',
  `NO_REWARD_IMAGE_FILE_ID` int(11) DEFAULT NULL COMMENT '노 리워드 이미지 파일 아이디',
  `NO_REWARD_BUTTON_TITLE` varchar(100) DEFAULT NULL COMMENT '노 리워드 확인 버튼명',
  `FAIL_TITLE` varchar(100) DEFAULT NULL COMMENT '실패 제목',
  `FAIL_MESSAGE` varchar(200) DEFAULT NULL COMMENT '실패 메시지',
  `FAIL_IMAGE_FILE_ID` int(11) DEFAULT NULL COMMENT '실패 이미지 파일 아이디',
  `FAIL_BUTTON_TITLE` varchar(20) DEFAULT NULL COMMENT '실패 확인 버튼명',
  `CREATE_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '등록자',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일시',
  `UPDATE_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`CAMPAIGN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Web Link';

DROP TABLE IF EXISTS `tb_mmt_deeplink`;

CREATE TABLE `tb_mmt_deeplink` (
  `CAMPAIGN_ID` int(11) NOT NULL DEFAULT '0' COMMENT '캠페인 아이디',
  `CALLBACK_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '딥링크 콜백 코드',
  `DEEPLINK_WEB_USE_YN` varchar(1) NOT NULL DEFAULT 'Y' COMMENT '딥링크 웹카드 사용 여부',
  `DEEPLINK_WEB_TITLE` varchar(100) DEFAULT NULL COMMENT '딥링크 웹카드 제목',
  `DEEPLINK_WEB_URL` varchar(100) DEFAULT NULL COMMENT '딥링크 웹카드 URL',
  `REWARD_USE_YN` varchar(1) NOT NULL DEFAULT 'Y' COMMENT '리워드 사용여부',
  `NO_REWARD_TITLE` varchar(100) DEFAULT NULL COMMENT '노 리워드 제목',
  `NO_REWARD_MESSAGE` varchar(200) DEFAULT NULL COMMENT '노 리워드 메시지',
  `NO_REWARD_IMAGE_FILE_ID` int(11) DEFAULT NULL COMMENT '노 리워드 이미지 파일 아이디',
  `NO_REWARD_BUTTON_TITLE` varchar(40) DEFAULT NULL COMMENT '노 리워드 확인 버튼명',
  `FAIL_TITLE` varchar(100) DEFAULT NULL COMMENT '실패 제목',
  `FAIL_MESSAGE` varchar(200) DEFAULT NULL COMMENT '실패 메시지',
  `FAIL_IMAGE_FILE_ID` int(11) DEFAULT NULL COMMENT '실패 이미지 파일 아이디',
  `FAIL_BUTTON_TITLE` varchar(40) DEFAULT NULL COMMENT '실패 확인 버튼명',
  `CREATE_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '등록자',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일시',
  `UPDATE_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`CAMPAIGN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Deep Link';

DROP TABLE IF EXISTS `tb_mmt_deeplink_callback`;

CREATE TABLE `tb_mmt_deeplink_callback` (
  `CALLBACK_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '딥링크 콜백 코드',
  `CALLBACK_TITLE` varchar(100) NOT NULL DEFAULT '' COMMENT '딥링크 콜백명',
  `CALLBACK_DESC` varchar(200) DEFAULT NULL COMMENT '딥링크 설명',
  PRIMARY KEY (`CALLBACK_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Deep Link 콜백';

DROP TABLE IF EXISTS `tb_mmt_jackpot`;

CREATE TABLE `tb_mmt_jackpot` (
  `CAMPAIGN_ID` int(11) NOT NULL DEFAULT '0' COMMENT '캠페인 아이디',
  `PROBABILITY` float(4,2) DEFAULT '0.00' COMMENT '당첨 확률',
  `JACKPOT_TITLE` varchar(100) NOT NULL DEFAULT '' COMMENT 'Jackpot 제목',
  `JACKPOT_MESSAGE` varchar(200) NOT NULL DEFAULT '' COMMENT 'Jackpot 메시지',
  `FAIL_TITLE` varchar(100) DEFAULT NULL COMMENT '실패 제목',
  `FAIL_MESSAGE` varchar(200) DEFAULT NULL COMMENT '실패 메시지',
  `FAIL_IMAGE_FILE_ID` int(11) DEFAULT NULL COMMENT '실패 이미지 파일 아이디',
  `FAIL_BUTTON_TITLE` varchar(40) DEFAULT NULL COMMENT '실패 버튼명',
  `CREATE_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '등록자',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일시',
  `UPDATE_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`CAMPAIGN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Jackpot';

DROP TABLE IF EXISTS `tb_mmt_stamp`;

CREATE TABLE `tb_mmt_stamp` (
  `CAMPAIGN_ID` int(11) NOT NULL DEFAULT '0' COMMENT '캠페인 아이디',
  `STAMP_COUNT` int(11) NOT NULL DEFAULT '0' COMMENT '스탬프 개수',
  `WARN_NOTI_TITLE` varchar(100) DEFAULT NULL COMMENT '경고 노티 제목',
  `WARN_NOTI_MESSAGE` varchar(200) DEFAULT NULL COMMENT '경고 노티 메시지',
  `WARN_NOTI_IMAGE_FILE_ID` int(11) DEFAULT NULL COMMENT '경고 노티 이미지 파일 아이디',
  `TITLE` varchar(100) NOT NULL DEFAULT '' COMMENT '제목',
  `MESSAGE1` varchar(200) NOT NULL DEFAULT '' COMMENT '메시지1',  
  `MESSAGE2` varchar(200) NOT NULL DEFAULT '' COMMENT '메시지2',  
  `MESSAGE3` varchar(200) NOT NULL DEFAULT '' COMMENT '메시지3',  
  `MESSAGE4` varchar(200) NOT NULL DEFAULT '' COMMENT '메시지4',  
  `MESSAGE5` varchar(200) NOT NULL DEFAULT '' COMMENT '메시지5',
  `CONFIRM_BUTTON_TITLE` varchar(40) NOT NULL DEFAULT '' COMMENT '확인 버튼명',
  `CREATE_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '등록자',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일시',
  `UPDATE_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`CAMPAIGN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='스탬프';

DROP TABLE IF EXISTS `tb_mmt_campaign_daily_target`;

CREATE TABLE `tb_mmt_campaign_daily_target` (
  `CAMPAIGN_ID` int(11) NOT NULL DEFAULT '0' COMMENT '캠페인 아이디',
  `YMD` varchar(8) NOT NULL DEFAULT '' COMMENT '년월일',
  `TARGET_COUNT` int(11) NOT NULL DEFAULT '0' COMMENT '목표 수량',
  `FORWARD_COUNT` int(11) DEFAULT NULL COMMENT '이월 수량',
  `CREATE_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '등록자',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일시',
  `UPDATE_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`CAMPAIGN_ID`,`YMD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='캠페인 일별 목표관리';

DROP TABLE IF EXISTS `tb_mmt_campaign_moment`;

CREATE TABLE `tb_mmt_campaign_moment` (
  `CAMPAIGN_ID` int(11) NOT NULL DEFAULT '0' COMMENT '캠페인 아이디',
  `MOMENT_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '모멘티 코드',
  `MOMENT_ID` int(11) NOT NULL DEFAULT '0' COMMENT '모멘티 아이디',
  PRIMARY KEY (`CAMPAIGN_ID`,`MOMENT_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='캠페인 모멘티';

DROP TABLE IF EXISTS `tb_mmt_user`;

CREATE TABLE `tb_mmt_user` (
  `USER_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '사용자 아이디',
  `USER_KEY` varchar(100) NOT NULL DEFAULT '' COMMENT 'User Key',
  `AGE` int(11) DEFAULT NULL COMMENT '나이',
  `GENDER_CODE` varchar(20) DEFAULT NULL COMMENT '성별 코드',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일시',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `UK_USER_KEY` (`USER_KEY`)
) ENGINE=InnoDB AUTO_INCREMENT=20674 DEFAULT CHARSET=utf8 COMMENT='사용자';

DROP TABLE IF EXISTS `tb_mmt_user_device`;

CREATE TABLE `tb_mmt_user_device` (
  `USER_ID` int(11) NOT NULL DEFAULT '0' COMMENT '사용자 아이디',
  `OS_CODE` varchar(20) DEFAULT NULL COMMENT 'O.S 코드',
  `OS_VERSION` varchar(20) DEFAULT NULL COMMENT 'O.S 버전',
  `DEVICE_MODEL_NAME` varchar(40) DEFAULT NULL COMMENT '디바이스 모델명',
  `NETWORK_OPERATOR` varchar(20) DEFAULT NULL COMMENT '통신사 코드',
  `CREATE_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '등록일시',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='사용자 디바이스';

DROP TABLE IF EXISTS `tb_mmt_user_app`;

CREATE TABLE `tb_mmt_user_app` (
  `USER_ID` int(11) NOT NULL DEFAULT '0' COMMENT '사용자 아이디',
  `APP_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '앱 코드',
  `MOMENT_APP_VERSION` varchar(20) DEFAULT NULL COMMENT '모멘티 앱 버전',
  `APP_VERSION` varchar(20) DEFAULT NULL COMMENT '앱 버전',
  `MOMENT_ON_OFF` varchar(20) NOT NULL DEFAULT 'ON' COMMENT '모멘티 On/Off',
  `REFUSE_COUNT` int(11) NOT NULL DEFAULT '0' COMMENT '모멘티 거절 횟수',
  `CREATE_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '등록일시',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`USER_ID`,`APP_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='사용자 설치 앱';

DROP TABLE IF EXISTS `tb_mmt_stamp_history`;

CREATE TABLE `tb_mmt_stamp_history` (
  `CAMPAIGN_ID` int(11) NOT NULL DEFAULT '0' COMMENT '캠페인 아이디',
  `USER_ID` int(11) NOT NULL DEFAULT '0' COMMENT '사용자 아이디',
  `CREATE_YMD` varchar(8) NOT NULL DEFAULT '' COMMENT '등록년월일',
  `CREATE_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '등록일시',
  PRIMARY KEY (`CAMPAIGN_ID`,`USER_ID`,`CREATE_YMD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='스탬프 이력';

DROP TABLE IF EXISTS `tb_mmt_stamp_warn_history`;

CREATE TABLE `tb_mmt_stamp_warn_history` (
  `CAMPAIGN_ID` int(11) NOT NULL DEFAULT '0' COMMENT '캠페인 아이디',
  `USER_ID` int(11) NOT NULL DEFAULT '0' COMMENT '사용자 아이디',
  `RECEIVE_YMD` varchar(8) NOT NULL DEFAULT '' COMMENT '수신년월일',
  `CREATE_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '등록일시',
  PRIMARY KEY (`CAMPAIGN_ID`,`USER_ID`,`RECEIVE_YMD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='스탬프 경고 이력';

DROP TABLE IF EXISTS `tb_mmt_campaign_join`;

CREATE TABLE `tb_mmt_campaign_join` (
  `CAMPAIGN_ID` int(11) NOT NULL DEFAULT '0' COMMENT '캠페인 아이디',
  `USER_ID` int(11) NOT NULL DEFAULT '0' COMMENT '사용자 아이디',
  `CURRENT_STATUS_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '참여 상태 코드',
  `PREV_STATUS_CODE` varchar(20) DEFAULT NULL COMMENT '참여 이전 상태 코드',
  `JOIN_COUNT` int(11) DEFAULT NULL COMMENT '참여횟수',
  `COUPON_DISPLAY_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '쿠폰노출상태코드',
  `MOMENT_ID` int(11) NOT NULL DEFAULT '0' COMMENT '모멘티 아이디',
  `CREATE_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '등록일시',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`CAMPAIGN_ID`,`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='캠페인 참여';

DROP TABLE IF EXISTS `tb_mmt_coupon_mapping`;

CREATE TABLE `tb_mmt_coupon_mapping` (
  `USER_ID` int(11) NOT NULL DEFAULT '0' COMMENT 'tkdydwk dkdlel',
  `COUPON_ID` int(11) NOT NULL DEFAULT '0' COMMENT '쿠폰고유아이디',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일시',
  PRIMARY KEY (`USER_ID`,`COUPON_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='쿠폰 수령';

DROP TABLE IF EXISTS `tb_mmt_campaign_targeting`;

CREATE TABLE `tb_mmt_campaign_targeting` (
  `CAMPAIGN_ID` int(11) NOT NULL DEFAULT '0' COMMENT '캠페인 아이디',
  `TOTAL_COUNT` int(11) DEFAULT NULL COMMENT '타겟팅 대상 수',
  `ESTIMATE_COUNT` int(11) DEFAULT NULL COMMENT '예측 수',
  `PROGRESS_STATUS_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '진행 상태 코드',
  `CREATE_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '등록일시',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '수정일시',
  `BATCH_TIME` datetime DEFAULT NULL COMMENT '배치일시',
  `USER_PARAGRAPH_ID` int(11) DEFAULT NULL COMMENT 'User Targeting Paragraph 아이디',
  `DATA_PARAGRAPH_ID` int(11) DEFAULT NULL COMMENT 'Data Targeting Paragraph 아이디',
  PRIMARY KEY (`CAMPAIGN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='캠페인 타겟팅';

DROP TABLE IF EXISTS `tb_mmt_campaign_targeting_user`;

CREATE TABLE `tb_mmt_campaign_targeting_user` (
  `CAMPAIGN_ID` int(11) NOT NULL DEFAULT '0' COMMENT '캠페인 아이디',
  `USER_ID` int(11) NOT NULL DEFAULT '0' COMMENT '사용자 아이디',
  `CREATE_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '등록일시',
  PRIMARY KEY (`CAMPAIGN_ID`, `USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='캠페인 타겟팅 유저';

DROP TABLE IF EXISTS `tb_mmt_user_tag`;

CREATE TABLE `tb_mmt_user_tag` (
  `TAG_ID` int(11) NOT NULL DEFAULT '0' COMMENT '태그 아이디',
  `TAG_NAME` varchar(100) NOT NULL DEFAULT '' COMMENT '태그명',
  `TAG_TITLE` varchar(200) NOT NULL DEFAULT '' COMMENT '태그 제목',
  `TAG_TITLE_FOR_HTML` varchar(200) NOT NULL DEFAULT '' COMMENT '태그 제목 HTML',
  `TAG_DESC` varchar(200) DEFAULT NULL COMMENT '태그 설명',
  `TAG_PARAMETER_DESC` varchar(200) DEFAULT NULL COMMENT '태그 파라미터 설명',
  `SEQ` int(11) NOT NULL DEFAULT '1' COMMENT '순번',
  `REALTIME_YN` varchar(1) NOT NULL DEFAULT 'N' COMMENT '실시간 여부',
  PRIMARY KEY (`TAG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='User Tag';

DROP TABLE IF EXISTS `tb_mmt_user_paragraph`;

CREATE TABLE `tb_mmt_user_paragraph` (
  `USER_PARAGRAPH_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'User Targeting Paragraph 아이디',
  `PROGRESS_STATUS_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '진행 상태 코드',
  `COUNT` int(11) DEFAULT NULL COMMENT '대상 수',
  `ESTIMATE_COUNT` int(11) DEFAULT NULL COMMENT '예측 수',
  `BATCH_TIME` datetime DEFAULT NULL COMMENT '배치일시',
  `CREATE_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '등록일시',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`USER_PARAGRAPH_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=42 DEFAULT CHARSET=utf8 COMMENT='User Targeting Paragraph';

DROP TABLE IF EXISTS `tb_mmt_user_sentence`;

CREATE TABLE `tb_mmt_user_sentence` (
  `USER_PARAGRAPH_ID` int(11) NOT NULL DEFAULT '0' COMMENT 'User Targeting Paragraph 아이디',
  `SEQ` int(11) NOT NULL DEFAULT '1' COMMENT '순번',
  `GROUP_NO` int(11) NOT NULL DEFAULT '1' COMMENT '그룹 번호',
  `TAG_ID` int(11) NOT NULL DEFAULT '0' COMMENT '태그 아이디',
  `SEQ_IN_GROUP` int(11) NOT NULL DEFAULT '1' COMMENT '그룹 내 순번',
  `OPTIONS` varchar(100) DEFAULT NULL COMMENT '옵션',
  `CONJUNCTION_CODE` varchar(20) DEFAULT NULL COMMENT '접속사 코드',
  `PROGRESS_STATUS_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '진행 상태 코드',
  `COUNT` int(11) DEFAULT NULL COMMENT '대상 수',
  `ESTIMATE_COUNT` int(11) DEFAULT NULL COMMENT '예측 수',
  `BATCH_TIME` datetime DEFAULT NULL COMMENT '배치일시',
  `CREATE_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '등록일시',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`USER_PARAGRAPH_ID`,`SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='User Targeting Sentence';

DROP TABLE IF EXISTS `tb_mmt_user_sentence_user`;

CREATE TABLE `tb_mmt_user_sentence_user` (
  `USER_PARAGRAPH_ID` int(11) NOT NULL DEFAULT '0' COMMENT 'User Targeting Paragraph 아이디',
  `SEQ` int(11) NOT NULL DEFAULT '1' COMMENT '순번',
  `USER_ID` int(11) NOT NULL COMMENT '사용자 아이디',
  `CREATE_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '등록일시',
  PRIMARY KEY (`USER_PARAGRAPH_ID`,`SEQ`, `USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='User Targeting Sentence 대상자';

DROP TABLE IF EXISTS `tb_mmt_data_tag`;

CREATE TABLE `tb_mmt_data_tag` (
  `TAG_ID` int(11) NOT NULL DEFAULT '0' COMMENT '태그 아이디',
  `TAG_NAME` varchar(100) NOT NULL DEFAULT '' COMMENT '태그명',
  `TAG_TITLE` varchar(200) NOT NULL DEFAULT '',
  `TAG_TITLE_FOR_HTML` varchar(200) NOT NULL DEFAULT '' COMMENT '태그 제목 HTML',
  `TAG_DESC` varchar(200) DEFAULT NULL COMMENT '태그 설명',
  `TAG_PARAMETER_DESC` varchar(200) DEFAULT NULL COMMENT '태그 파라미터 설명',
  `TAG_TYPE_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '태그 타입 코드',
  `SEQ` int(11) NOT NULL DEFAULT '1' COMMENT '순번',
  PRIMARY KEY (`TAG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Data Tag';

DROP TABLE IF EXISTS `tb_mmt_realtime_data_tag`;

CREATE TABLE `tb_mmt_realtime_data_tag` (
  `TAG_ID` int(11) NOT NULL DEFAULT '0' COMMENT '태그 아이디',
  `MOMENT_ID` int(11) NOT NULL DEFAULT '0' COMMENT '모멘티 아이디',
  PRIMARY KEY (`TAG_ID`, `MOMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='실시간 가능 Data Tag 모멘티';

DROP TABLE IF EXISTS `tb_mmt_data_paragraph`;

CREATE TABLE `tb_mmt_data_paragraph` (
  `DATA_PARAGRAPH_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Data Targeting Paragraph 아이디',
  `PROGRESS_STATUS_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '진행 상태 코드',
  `COUNT` int(11) DEFAULT NULL COMMENT '대상 수',
  `ESTIMATE_COUNT` int(11) DEFAULT NULL COMMENT '예측 수',
  `BATCH_TIME` datetime DEFAULT NULL COMMENT '배치일시',
  `CREATE_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '등록일시',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`DATA_PARAGRAPH_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COMMENT='Data Targeting Paragraph';

DROP TABLE IF EXISTS `tb_mmt_data_sentence`;

CREATE TABLE `tb_mmt_data_sentence` (
  `DATA_PARAGRAPH_ID` int(11) NOT NULL DEFAULT '0' COMMENT 'Data Targeting Paragraph 아이디',
  `SEQ` int(11) NOT NULL DEFAULT '1' COMMENT '순번',
  `GROUP_NO` int(11) NOT NULL DEFAULT '1' COMMENT '그룹 번호',
  `TAG_ID` int(11) NOT NULL DEFAULT '0' COMMENT '태그 아이디',
  `SEQ_IN_GROUP` int(11) NOT NULL DEFAULT '1' COMMENT '그룹 내 순번',
  `OPTIONS` varchar(100) DEFAULT NULL COMMENT '옵션',
  `CONJUNCTION_CODE` varchar(20) DEFAULT NULL COMMENT '접속사 코드',
  `REALTIME_YN` varchar(1) NOT NULL DEFAULT 'N' COMMENT '실시간여부',
  `PROGRESS_STATUS_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '진행 상태 코드',
  `COUNT` int(11) DEFAULT NULL COMMENT '대상 수',
  `ESTIMATE_COUNT` int(11) DEFAULT NULL COMMENT '예측 수',
  `BATCH_TIME` datetime DEFAULT NULL COMMENT '배치일시',
  `CREATE_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '등록일시',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`DATA_PARAGRAPH_ID`,`SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Data Targeting Sentence';

DROP TABLE IF EXISTS `tb_mmt_data_sentence_user`;

CREATE TABLE `tb_mmt_data_sentence_user` (
  `DATA_PARAGRAPH_ID` int(11) NOT NULL DEFAULT '0' COMMENT 'Data Targeting Paragraph 아이디',
  `SEQ` int(11) NOT NULL DEFAULT '1' COMMENT '순번',
  `USER_ID` int(11) NOT NULL COMMENT '사용자 아이디',
  `CREATE_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '등록일시',
  PRIMARY KEY (`DATA_PARAGRAPH_ID`,`SEQ`, `USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Data Targeting Sentence 대상자';

DROP TABLE IF EXISTS `tb_mmt_information_targeting`;

CREATE TABLE `tb_mmt_information_targeting` (
  `INFORMATION_ID` int(11) NOT NULL DEFAULT '0' COMMENT '인포메이션 아이디',
  `TOTAL_COUNT` int(11) DEFAULT NULL COMMENT '타겟팅 대상 수',
  `PROGRESS_STATUS_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT '진행 상태 코드',
  `CREATE_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '등록일시',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '수정일시',
  `BATCH_TIME` datetime DEFAULT NULL COMMENT '배치일시',
  `USER_PARAGRAPH_ID` int(11) DEFAULT NULL COMMENT 'User Targeting Paragraph 아이디',
  `DATA_PARAGRAPH_ID` int(11) DEFAULT NULL COMMENT 'Data Targeting Paragraph 아이디',
  PRIMARY KEY (`INFORMATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='인포메이션 타겟팅';

DROP TABLE IF EXISTS `tb_mmt_information_targeting_user`;

CREATE TABLE `tb_mmt_information_targeting_user` (
  `INFORMATION_ID` int(11) NOT NULL DEFAULT '0' COMMENT '인포메이션 아이디',
  `USER_ID` int(11) NOT NULL DEFAULT '0' COMMENT '사용자 아이디',
  `CREATE_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '등록일시',
  PRIMARY KEY (`INFORMATION_ID`, `USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='인포메이션 타겟팅 유저';

DROP TABLE IF EXISTS `tb_mmt_poi`;

CREATE TABLE `tb_mmt_poi` (
  `POI_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'POI 아이디',
  `POI_NAME` varchar(100) NOT NULL DEFAULT '' COMMENT 'POI명',
  `POI_DESC` varchar(200) DEFAULT NULL COMMENT 'POI 설명',
  `SEARCH_KM` int(11) NOT NULL DEFAULT '0' COMMENT '검색반경(KM)',
  `CREATE_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '등록일시',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`POI_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='POI';

DROP TABLE IF EXISTS `tb_mmt_poi_branch`;

CREATE TABLE `tb_mmt_poi_branch` (
  `POI_ID` int(11) NOT NULL DEFAULT '0' COMMENT 'POI 아이디',
  `SEQ` int(11) NOT NULL DEFAULT '1' COMMENT '순번',
  `BRANCH_NAME` varchar(40) NOT NULL DEFAULT '' COMMENT '지점명',
  `BRANCH_DESC` varchar(200) DEFAULT NULL COMMENT '지점 설명',
  `LATITUDE` double DEFAULT NULL COMMENT '위도',
  `LONGITUDE` double DEFAULT NULL COMMENT '경도',
  `CREATE_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '등록일시',
  PRIMARY KEY (`POI_ID`,`SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='POI 지점';

DROP TABLE IF EXISTS `tb_mmt_place`;

CREATE TABLE `tb_mmt_place` (
  `PLACE_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '등록 지역 아이디',
  `PLACE_NAME` varchar(100) NOT NULL DEFAULT '' COMMENT '등록 지역명',
  `LATITUDE` double NOT NULL DEFAULT '0' COMMENT '위도',
  `LONGITUDE` double NOT NULL DEFAULT '0' COMMENT '경도',
  `ROUND` int(11) NOT NULL DEFAULT '0' COMMENT '반경(m)',
  PRIMARY KEY (`PLACE_ID`),
  UNIQUE KEY `UK_PLACE_NAME` (`PLACE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='등록 지역';

DROP TABLE IF EXISTS `tb_mmt_information_targeting`;

CREATE TABLE `tb_mmt_information_targeting` (
  `INFORMATION_ID` int(11) NOT NULL DEFAULT '0' COMMENT '인포메이션 아이디',
  `TOTAL_COUNT` int(11) DEFAULT NULL COMMENT '전체 대상수',
  `ESTIMATE_COUNT` int(11) DEFAULT NULL COMMENT '예측 대상수',
  `PROGRESS_STATUS_CODE` varchar(20) DEFAULT NULL COMMENT '진행 상태 코드',
  `CREATE_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '등록일시',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '수정일시',
  `BATCH_TIME` datetime DEFAULT NULL COMMENT '배치 일시',
  `DATA_PARAGRAPH_ID` int(11) DEFAULT NULL COMMENT 'Data Targeting Paragraph 아이디',
  `USER_PARAGRAPH_ID` int(11) DEFAULT NULL COMMENT 'Data Targeting Paragraph 아이디',
  PRIMARY KEY (`INFORMATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='인포메이션 타겟팅';

DROP TABLE IF EXISTS `tb_mmt_information_target_user`;

CREATE TABLE `tb_mmt_information_target_user` (
  `INFORMATION_ID` int(11) NOT NULL DEFAULT '0' COMMENT '인포메이션 아이디',
  `USER_ID` int(11) NOT NULL DEFAULT '0' COMMENT '사용자 아이디',
  `CREATE_TIME` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '등록일시',
  PRIMARY KEY (`INFORMATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='인포메이션 타겟팅 사용자';

DROP TABLE IF EXISTS `tb_mmt_sdk_version`;

CREATE TABLE `tb_mmt_sdk_version` (
  `SDK_VERSION_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'SDK 버전 아이디',
  `SDK_VERSION` varchar(20) NOT NULL DEFAULT '' COMMENT 'SDK 버전',
  `SDK_VERSION_NAME` varchar(100) NOT NULL DEFAULT '' COMMENT 'SDK 버전명',
  `SDK_VERSION_DESC` text COMMENT 'SDK 버전 설명',
  `CREATE_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '등록자',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일시',
  `UPDATE_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`SDK_VERSION_ID`),
  KEY `UK_SDK_VERSION_NAME` (`SDK_VERSION_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='SDK 버전 정보';

DROP TABLE IF EXISTS `tb_mmt_campaign_whitelist`;

CREATE TABLE `tb_mmt_campaign_whitelist` (
  `CAMPAIGN_ID` int(11) NOT NULL DEFAULT '0' COMMENT '캠페인 아이디',
  `ON_OFF_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT 'On/Off 코드',
  `CREATE_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '등록자',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일시',
  `UPDATE_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`CAMPAIGN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='캠페인 수신 지정';

DROP TABLE IF EXISTS `tb_mmt_campaign_whitelist_user`;

CREATE TABLE `tb_mmt_campaign_whitelist_user` (
  `CAMPAIGN_ID` int(11) NOT NULL DEFAULT '0' COMMENT '캠페인 아이디',
  `USER_KEY` varchar(100) NOT NULL DEFAULT '0' COMMENT 'User Key',
  PRIMARY KEY (`CAMPAIGN_ID`, `USER_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='캠페인 수신 지정 사용자';

DROP TABLE IF EXISTS `tb_mmt_information_whitelist`;

CREATE TABLE `tb_mmt_information_whitelist` (
  `INFORMATION_ID` int(11) NOT NULL DEFAULT '0' COMMENT '인포메이션 아이디',
  `ON_OFF_CODE` varchar(20) NOT NULL DEFAULT '' COMMENT 'On/Off 코드',
  `CREATE_ID` varchar(20) NOT NULL DEFAULT '' COMMENT '등록자',
  `CREATE_DATE` varchar(14) NOT NULL DEFAULT '' COMMENT '등록일시',
  `UPDATE_ID` varchar(20) DEFAULT NULL COMMENT '수정자',
  `UPDATE_DATE` varchar(14) DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`INFORMATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='인포메이션 수신 지정';

DROP TABLE IF EXISTS `tb_mmt_information_whitelist_user`;

CREATE TABLE `tb_mmt_information_whitelist_user` (
  `INFORMATION_ID` int(11) NOT NULL DEFAULT '0' COMMENT '인포메이션 아이디',
  `USER_KEY` varchar(100) NOT NULL DEFAULT '0' COMMENT 'User Key',
  PRIMARY KEY (`INFORMATION_ID`, `USER_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='인포메이션 수신 지정 사용자';

CREATE TABLE `tb_mmt_event` (
  `EVENT_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '이벤트 아이디',
  `EVENT_SUMMARY` varchar(45) NOT NULL COMMENT '이벤트 요약',
  `EVENT_TITLE` varchar(45) NOT NULL COMMENT '이벤트 제목',
  `EVENT_IMAGE_ID` int(11) NOT NULL COMMENT '이벤트 이미지 아이디 (tb_mmt_file)',
  `DISP_START_YMD` varchar(8) NOT NULL COMMENT '노출 시작일',
  `DISP_END_YMD` varchar(8) NOT NULL COMMENT '노출 종료일',
  `STATUS_CODE` varchar(6) NOT NULL DEFAULT 'USE_Y' COMMENT '사용여부 USE_Y or USE_N',
  `DISPLAY_PRIORITY` int(11) NOT NULL DEFAULT '1' COMMENT '우선순위',
  PRIMARY KEY (`event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='이벤트';


